from typing import Optional


def detect_language(file_path: str) -> Optional[str]:
    """Detect programming language from file extension"""
    if not file_path:
        return None

    # Get file extension
    ext = file_path.split(".")[-1].lower() if "." in file_path else ""

    # Language mapping
    lang_map = {
        "py": "Python",
        "js": "JavaScript",
        "ts": "TypeScript",
        "jsx": "JavaScript",
        "tsx": "TypeScript",
        "java": "Java",
        "c": "C",
        "cpp": "C++",
        "cc": "C++",
        "cxx": "C++",
        "h": "C",
        "hpp": "C++",
        "cs": "C#",
        "php": "PHP",
        "rb": "Ruby",
        "go": "Go",
        "rs": "Rust",
        "swift": "Swift",
        "kt": "Kotlin",
        "scala": "Scala",
        "clj": "Clojure",
        "hs": "Haskell",
        "ml": "OCaml",
        "fs": "F#",
        "erl": "Erlang",
        "ex": "Elixir",
        "lua": "Lua",
        "r": "R",
        "m": "Objective-C",
        "mm": "Objective-C++",
        "pl": "Perl",
        "sh": "Shell",
        "bash": "Shell",
        "zsh": "Shell",
        "fish": "Shell",
        "ps1": "PowerShell",
        "bat": "Batch",
        "cmd": "Batch",
        "sql": "SQL",
        "html": "HTML",
        "htm": "HTML",
        "css": "CSS",
        "scss": "SCSS",
        "sass": "Sass",
        "less": "Less",
        "xml": "XML",
        "json": "JSON",
        "yaml": "YAML",
        "yml": "YAML",
        "toml": "TOML",
        "ini": "INI",
        "cfg": "Config",
        "conf": "Config",
        "md": "Markdown",
        "rst": "reStructuredText",
        "tex": "LaTeX",
        "dockerfile": "Dockerfile",
        "makefile": "Makefile",
        "cmake": "CMake",
        "gradle": "Gradle",
        "maven": "Maven",
        "pom": "Maven",
        "sbt": "SBT",
        "gemfile": "Ruby",
        "rakefile": "Ruby",
        "gemspec": "Ruby",
        "podfile": "Ruby",
        "cartfile": "Swift",
        "package": "Swift",
        "cargo": "Rust",
        "composer": "PHP",
        "pubspec": "Dart",
        "mix": "Elixir",
        "rebar": "Erlang",
        "stack": "Haskell",
        "cabal": "Haskell",
        "opam": "OCaml",
        "julia": "Julia",
        "jl": "Julia",
        "dart": "Dart",
        "vue": "Vue",
        "svelte": "Svelte",
        "astro": "Astro",
        "solid": "Solid",
        "elm": "Elm",
        "cljs": "ClojureScript",
        "coffee": "CoffeeScript",
        "litcoffee": "CoffeeScript",
        "iced": "IcedCoffeeScript",
        "pug": "Pug",
        "jade": "Pug",
        "haml": "Haml",
        "slim": "Slim",
        "erb": "ERB",
        "ejs": "EJS",
        "hbs": "Handlebars",
        "mustache": "Mustache",
        "twig": "Twig",
        "liquid": "Liquid",
        "njk": "Nunjucks",
        "nunjucks": "Nunjucks",
        "styl": "Stylus",
        "stylus": "Stylus",
        "postcss": "PostCSS",
        "graphql": "GraphQL",
        "gql": "GraphQL",
        "prisma": "Prisma",
        "proto": "Protocol Buffers",
        "thrift": "Thrift",
        "avro": "Avro",
        "capnp": "Cap'n Proto",
        "flatbuffers": "FlatBuffers",
        "msgpack": "MessagePack",
        "bson": "BSON",
        "cbor": "CBOR",
        "edn": "EDN",
        "cljc": "Clojure",
        "boot": "Boot",
        "lein": "Leiningen",
        "deps": "Clojure",
    }

    return lang_map.get(ext, None)
